# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample_test
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
end
